# -*- coding: utf-8 -*-
"""charts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qD9u8qWlRlE7z352U9IcVHBtJxEPGkxz
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.linspace(0,10,100)
y=np.sin(x)
z=np.cos(x)
print(x)

plt.plot(x,y)
plt.show()

plt.plot(x,z)
plt.show()

plt.plot(x,y)
plt.xlabel('angle')
plt.ylabel('sine value')
plt.title('sine wave')
plt.show()

x=np.linspace(-10,10,20)
y=x**2
plt.plot(x,y)
plt.show()

plt.plot(x,y,'b+')
plot.show()

x=np.linspane(-5,5,50)
plt.plot(x,np.sin(x), 'g-')
plt.plot(x,np.cos(x),)

fig=plt.figure()
ax=fig.add_axes([0,0,1,1])
languages = ['English','French','German','Spanish','Latin']
people=[100,50,150,40,70]
ax.bar(languages,people,color='orange')
plt.xlabel('LANGUAGES')
plt.ylabel('NUMBER OF PEOPLE')
plt.show()

fig1 = plt.figure()
ax = fig1.add_axes([0,0,1,1])
languages = ['English','French','Spanish', 'Latin','German']
people = [100, 50, 40, 70, 50]
myexplode=[0.2,0,0,0,0]
ax.pie(people, labels=languages, autopct='%1.1f%%', explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 30)
y = np.sin(x)
z = np.cos(x)
plt.scatter(x,y, color='red', marker='+')
plt.scatter(x,z, color='purple', marker='o')
plt.show()

fig3 = plt.figure()
ax = plt.axes(projection='3d')
z = 20 * np.random.random(100)
x = np.sin(z)
y = np.cos(z)
ax.scatter(x,y,z,c=z, cmap='Reds')
plt.show()

plt.hist(people, bins=5, color='red')
plt.xlabel('People')
plt.ylabel('Frequency')
plt.title('Distribution of People')
plt.show()

plt.grid(color='green', linestyle='-', linewidth=2)
plt.show()